name: Build First Container

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    # [ ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest

    steps:

      - name: Copy from repo into temp directory
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: docker build -f docker_images/dockerfile -t my-first-container .

      - name: Test the contaner
        run: docker run my-first-container
